```bsh
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/.gitignore
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/.prettierrc
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/CONTRIBUTING.md
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/eslint.config.mjs
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/package.json
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/README.md
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/pnpm-lock.yaml
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/tsconfig.json
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/tslint.json
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/typedoc.json
https://cdn.jsdelivr.net/gh/mathjax/mathjax-v3@4.0.0/LICENSE
